services:
  postgres:
    image: postgres:${PG_VERSION:-17}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_pglocks
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
